services:
  - type: web
    name: rider-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run render-start
    healthCheckPath: /api/riders
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
